class Country < ActiveHash::Base
  self.data = [
      {id: 0, name: ' where are you from ? '}, {id: 1, name: 'Afghanistan'}, {id: 2, name: 'Albania'},
      {id: 3, name: 'Algeria'}, {id: 4, name: 'Andorra'}, {id: 5, name: 'Angola'},
      {id: 6, name: 'Antigua and Barbuda'}, {id: 7, name: 'Argentina'}, {id: 8, name: 'Armenia'},
      {id: 9, name: 'Australia'}, {id: 10, name: 'Austria'}, {id: 11, name: 'Azerbaijan'},
      {id: 12, name: 'Bahamas'}, {id: 13, name: 'Bahrain'}, {id: 14, name: 'Bangladesh'},
      {id: 15, name: 'Barbados'}, {id: 16, name: 'Belarus'}, {id: 17, name: 'Belgium'},
      {id: 18, name: 'Belize'}, {id: 19, name: 'Benin'}, {id: 20, name: 'Bhutan'},
      {id: 21, name: 'Bolivia'}, {id: 22, name: 'Bosnia and Herzegovina'}, {id: 23, name: 'Botswana'},
      {id: 24, name: 'Brazil'}, {id: 25, name: 'Brunei Darussalam'}, {id: 26, name: 'Bulgaria'},
      {id: 27, name: 'Burkina Faso'}, {id: 28, name: 'Burundi'}, {id: 29, name: 'Cabo Verde'},
      {id: 30, name: 'Cambodia'}, {id: 31, name: 'Cameroon'}, {id: 32, name: 'Canada'},
      {id: 33, name: 'Central African Republic'}, {id: 34, name: 'Chad'}, {id: 35, name: 'Chile'},
      {id: 36, name: 'China'}, {id: 37, name: 'Colombia'}, {id: 38, name: 'Comoros'},
      {id: 39, name: 'Congo (Republic of the)'}, {id: 40, name: 'Costa Rica'}, {id: 41, name: 'Cote d’Ivoire'},
      {id: 42, name: 'Croatia'}, {id: 43, name: 'Cuba'}, {id: 44, name: 'Cyprus'},
      {id: 45, name: 'Czech Republic'}, {id: 46, name: 'Democratic People’s Republic of Korea'}, {id: 47, name: 'Democratic Republic of the Congo'},
      {id: 48, name: 'Denmark'}, {id: 49, name: 'Djibouti'}, {id: 50, name: 'Dominica'},
      {id: 51, name: 'Dominican Republic'}, {id: 52, name: 'Ecuador'}, {id: 53, name: 'Egypt'},
      {id: 54, name: 'El Salvador'}, {id: 55, name: 'Equatorial Guinea'}, {id: 56, name: 'Eritrea'},
      {id: 57, name: 'Estonia'}, {id: 58, name: 'Eswatini'}, {id: 59, name: 'Ethiopia'},
      {id: 60, name: 'Fiji'}, {id: 61, name: 'Finland'}, {id: 62, name: 'France'},
      {id: 63, name: 'Gabon'}, {id: 64, name: 'Gambia'}, {id: 65, name: 'Georgia'},
      {id: 66, name: 'Germany'}, {id: 67, name: 'Ghana'}, {id: 68, name: 'Greece'},
      {id: 69, name: 'Grenada'}, {id: 70, name: 'Guatemala'}, {id: 71, name: 'Guinea'},
      {id: 72, name: 'Guinea-Bissau'}, {id: 73, name: 'Guyana'}, {id: 74, name: 'Hait'},
      {id: 75, name: 'Honduras'}, {id: 76, name: 'Hungary'}, {id: 77, name: 'Iceland'},
      {id: 78, name: 'India'}, {id: 79, name: 'Indonesia'}, {id: 80, name: 'Iran'},
      {id: 81, name: 'Iraq'}, {id: 82, name: 'Ireland'}, {id: 83, name: 'Israe'},
      {id: 84, name: 'Italy'}, {id: 85, name: 'Jamaica'}, {id: 86, name: 'Japan'},
      {id: 87, name: 'Jordan'}, {id: 88, name: 'Kazakhstan'}, {id: 89, name: 'Kenya'},
      {id: 90, name: 'Kiribati'}, {id: 91, name: 'Kuwait'}, {id: 92, name: 'Kyrgyzstan'},
      {id: 93, name: 'Lao People’s Democratic Republic'}, {id: 94, name: 'Latvia'}, {id: 95, name: 'Lebanon'},
      {id: 96, name: 'Lesotho'}, {id: 97, name: 'Liberia'}, {id: 98, name: 'Libya'},
      {id: 99, name: 'Liechtenstein'}, {id: 100, name: 'Lithuania'}, {id: 101, name: 'Luxembourg'},
      {id: 102, name: 'Madagascar'}, {id: 103, name: 'Malawi'}, {id: 104, name: 'Malaysia'},
      {id: 105, name: 'Maldives'}, {id: 106, name: 'Mali'}, {id: 107, name: 'Malta'},
      {id: 108, name: 'Marshall Islands'}, {id: 109, name: 'Mauritania'}, {id: 110, name: 'Mauritius'},
      {id: 111, name: 'Mexico'}, {id: 112, name: 'Micronesia (Federated States of)'}, {id: 113, name: 'Monaco'},
      {id: 114, name: 'Mongolia'}, {id: 115, name: 'Montenegro'}, {id: 116, name: 'Morocco'},
      {id: 117, name: 'Mozambique'}, {id: 118, name: 'Myanmar'}, {id: 119, name: 'Namibia'},
      {id: 120, name: 'Nauru'}, {id: 121, name: 'Nepal'}, {id: 122, name: 'Netherlands'},
      {id: 123, name: 'New Zealand'}, {id: 124, name: 'Nicaragua'}, {id: 125, name: 'Niger'},
      {id: 126, name: 'Nigeria'}, {id: 127, name: 'North Macedonia'}, {id: 128, name: 'Norway'},
      {id: 129, name: 'Oman'}, {id: 130, name: 'Pakistan'}, {id: 131, name: 'Palau'},
      {id: 132, name: 'Panama'}, {id: 133, name: 'Papua New Guinea'}, {id: 134, name: 'Paraguay'},
      {id: 135, name: 'Peru'}, {id: 136, name: 'Philippines'}, {id: 137, name: 'Poland'},
      {id: 138, name: 'Portugal'}, {id: 139, name: 'Qatar'}, {id: 140, name: 'Republic of Korea'},
      {id: 141, name: 'Republic of Moldova'}, {id: 142, name: 'Romania'}, {id: 143, name: 'Russian Federation'},
      {id: 144, name: 'Rwanda'}, {id: 145, name: 'Saint Kitts and Nevis'}, {id: 146, name: 'Saint Lucia'},
      {id: 147, name: 'Saint Vincent and the Grenadines'}, {id: 148, name: 'Samoa'}, {id: 149, name: 'San Marino'},
      {id: 150, name: 'Sao Tome and Principe'}, {id: 151, name: 'Saudi Arabia'}, {id: 152, name: 'Senegal'},
      {id: 153, name: 'Serbia'}, {id: 154, name: 'Seychelles'}, {id: 155, name: 'Sierra Leone'},
      {id: 156, name: 'Singapore'}, {id: 157, name: 'Slovakia'}, {id: 158, name: 'Slovenia'},
      {id: 159, name: 'Solomon Islands'}, {id: 160, name: 'Somalia'}, {id: 161, name: 'South Africa'},
      {id: 162, name: 'South Sudan'}, {id: 163, name: 'Spain'}, {id: 164, name: 'Sri Lanka'},
      {id: 165, name: 'Sudan'}, {id: 166, name: 'Suriname'}, {id: 167, name: 'Sweden'},
      {id: 168, name: 'Switzerland'}, {id: 169, name: 'Syria'}, {id: 170, name: 'Tajikistan'},
      {id: 171, name: 'Thailand'}, {id: 172, name: 'Timor-Leste'}, {id: 173, name: 'Togo'},
      {id: 174, name: 'Tonga'}, {id: 175, name: 'Trinidad and Tobago'}, {id: 176, name: 'Tunisia'},
      {id: 177, name: 'Turkey'}, {id: 178, name: 'Turkmenistan'}, {id: 179, name: 'Tuvalu'},
      {id: 180, name: 'Uganda'}, {id: 181, name: 'Ukraine'}, {id: 182, name: 'United Arab Emirates'},
      {id: 183, name: 'United Kingdom'}, {id: 184, name: 'United Republic of Tanzania'}, {id: 185, name: 'United States of America'},
      {id: 186, name: 'Uruguay'}, {id: 187, name: 'Uzbekistan'}, {id: 188, name: 'Vanuatu'},
      {id: 189, name: 'Venezuela'}, {id: 190, name: 'Viet Nam'}, {id: 191, name: 'Yemen'},
      {id: 192, name: 'Zambia'}, {id: 193, name: 'Zimbabwe'}
  ]
end